# Gel electrophoresis is an analysis method implemented in all disciplines of life sciences. 
# The results of gel electrophoresis indicate the relative sizes of fragments, which is useful for restriction mapping and analyzing PCR fragments. 
# 1. Take an arbitrary DNA sequence from the NCBI (National Center for Biotechnology), between 1000 and 3000 nucleotides (letters).
# 2. Take 10 random samples from this sequence, between 100-3000 bases.
# 3. Store these samples in an array.
# 4. Simulate the migration of these DNA segments on the electrophoresis gel, based on their molecular weights.

import numpy as np
import matplotlib.pyplot as plt
import random

dna_sequence = """
CGTGAACCTTGCTTGTTTCTTCCTTTCCCCTGCTCTGCTTTCCCCAAGCTCAGCCTCTCGTCCGCTCTAT
ATTCTATCCACCATCGAACGGAAAAGCCCAAAAAATTCGAGCTCTTAAGCTTGCGAATTTCCGCCTTATT
TTTTCCCTGCGCACAGCATTGGAATCCCCTCCCATCTCTCTGATGCAATCTCACCAACCTATGCGATCTT
GATCTCCAACACCATGGCAGCGGCCGACGTGGACTTGGGGCAACTCTCCACGCATCTTGGCGTGCCGGAG
CCTGCTCTCAGCTCGCTCACGACCGAGCCTACCGTCGACCTTGTCCACGCTGTCCTCCAAGCCGTGGCAG
CCAAGGCGCGCGAGTTTGAGGTGATCTACTCTGAAAAGCTGCAGGTCGACATCGAGCTGGAGAACGTGAT
CCGGAGCTCCGAGGCACGATGCGAACAATTCAAGACCACCACCGACAAGTCCTTGAAGGAGGTCGAGGAA
GTTAGACAGAAGCTTCGAAACGAAGAGAATGATCGGCAAGCCCTCGAGAACGAACTTCAGACTCTGAGGT
CTTCCAGTGCATCGCATCAGACCGAAATCGAGACCTTACGGGAGCGCAACAGTTCCCTGGAAGCGTCAAA
TCGAGATGCCCTTTCGATCATCGATTCGAAGAACGCTGCCAACGCCGACCTGGCCGAGGAGCTTCAGAGG
CAGCATAAAAAGATTGTGCAGCTTAATCAGGAGATTGCGTCGCTGAGCCAAGCCGCCCAATCTGCCCAGG
CCACAGTGAGCAGTGCAAAGTTCCGTGAAGAATCAATCCAGCAGGAGCTCGAGCTGGCGCGACGAAACAA
CGAATGGCTGGAAAACGAACTCAAGGCGAAGAGTGCCGAAGCCCTCAAAACCCGAAAGGAGAAAGGCGCC
CGCATCTCCGAGCTCCAGCGACTGTACGACGACGCGAATTCGAATATCGAGTCGCTGACGCGCAGCGAGC
AGCAGCTTCGAAAGCGGCTGGACGAGGCACAGAAGAAAGCAGACGAGTCCCTGACCAAGGTGCAACAACT
CCAAGAATCGGCTTCTCGGGCCGAGGAGGGTTTCAAGCAGGAACTTGAATCGTCAAAGCGACTTGTCGAA
CTCAAGGATGAACAAGCCAAGACCCACAAGAAGAGGCTACAGGAGGTCGAGTTTAGACTTGAGCAAGTCA
AGGACGATGTAGTCGAGGAGGTTCGGGCGATCCGGCAAGCGCTTGAGAAGGAGAAGGAGGAGCACGCGCA
GACAGTACATCAGGCCCAGGAACTGCAATCTGAGATGGACCGGTTGCAGGCTGTCCTGTCGTCCCAGACA
GTTGAGCCAGGATCCGCGCCGCAGACCCCCCGACCGAACGGCTCTGTTTTCGGCCGTGCTGCATCCCCCT
TCGCCACCCCAGGATCTCTTCGCGGCAAGTCTGCCTTGCGTGCAAGCGATGCCATTGAGGAGCTGTATAA
TGTCAAGGGGCAGTTGAGCGGGGAAAAGCGACGGAACAAGAAGCTCCAGGAAGAACTCGACGACCTTGCA
AGCATCTTGGAGGCCAAGGCACCCGAAATCGACGAGGCGAATGCCGAAGCCGAGCGTCTGAGGAACGAAG
CCATCCAGATGTCCCAGATCATGGAGCAGTCCTACCAGGAACGCGACTTTGCAACCAAGGCTGCCAGAAA
GGCAGAGGCGGCCGCCTCTAGGGCGCAGACTGAACTCAACATACTACAAGCCCAGCTTCGCGACCTCAGC
ACCCAAGTGCACGTCCTCATATTTAATATCCACGCCCAGGAGAAGGGCCTGGACCAACTCAGCGAGGAGG
AGACGAGGCAGTATGAGCGTATCTCGCGAGGAGAAGTTGCGGAGGACTCCTTGGCAGATCTCTCGCCTAC
CCACAAGTTCATCACGGAACGATTCGTTGCCTTCAAGGACATCTACGAACTCCAGGCCAAGAACCAAGAA
CTCCTGAGACTTACACGCGAGCTTGCCGACAAGATGGAGAAGGAGGAAGCCCTGGCAGAGCAGCATCAGG
CGGCCGAGGCCCATGAAGAGGTCGAGAGCCTCCGTGGCACAGTCTCTACCTTGCAAGACGAGGTCAAGTC
CATCACTGTGCGCATGAAGAGCTACATGACCGAGCGAGACATGTTCCGCCGCATGCTGCAGCAGAAGGCG
ACCCCAGCCGAGATCCACGCAGCCCTAGGGGCGTCCGGCGACGGCAGCCAGCGGGAGGTCCTCGCAAGTA
TCGAGCAAAACACCGCGGCCGAGGAGGCCGACCTGGTTGTCGCCCTTCGAGAATTGCAAGGCCAGTTTGA
TTCTTACCGAAATGACCAGACTACCGACCGAAAGGCGCTCAAGGATCAGATCGACAGGCTATCGTCAGAG
AAGTCCTCCCTGCAGGCCGAGGTTTCGAGGGTTGGCAGCCAGCTCACTCTCGCCACTGAACGATACGGCA
TCCTGCAGTCCAACTTACAGGCGATGCAGGTTGAAGGCAAGGAGCTGCAGAAGAGGAATCAGGCCCTTTC
AGAAACGTCTGCCAAACAGGATATCCGCACCCAGCAGGTTGCGCAGGAGCTTGTGGAGGTTCGAGAGTTG
CATGAGAGCATGCGGAATGAGAACGCAAATCTCAAGGCCGAGAAGACTCTGTGGAAGAGCATTCAAGAAC
GTCTCCATCAGGATAACGAGAACTTGGTCCAGGAGAAGGCTAGGCTCAATTCTCTGCTTTCGAACCAGCA
GTCTCTACAGAATGAGAGAGAGCTGGGCGAGGCGGAGACGAGACGACGACTGCAGAACCAGACTGACACT
CTGGAGGCCGAGCTGACCGCCACAAAACGCAAACTCGAGGCCGAGAGAGAGGAGTCGAGGAAGTCTCAGC
TGAGGAGAGAGTTCGATGGCCAGCAGTCGCAGAAGAGGATCGACGAGCTGACCTCGTCTCTCGGACAACT
CAAGCAAGAGAATGTGGCCCTCAAGACGAGCCGTGACCATCTCCAAGCCCGAGTCGATGAACTGACCGTT
GAAGTTCGGAGCGCCGAGGAGCGTGCGCAGCGGCTGCGCCCAATCCCGACTCCACGAGCCGCAGCACCAG
CAACCGCAGAGCAGGCAGGTGGCGACGATGATTCGGAAGCTCGCATCCAAGAATTGGAAGCCGAGACTTC
TGAGCTCAAGACCAGCCTCGAGCTGGCCAACGTACATCTCGAGAACGCCAGGCAGCAGGGTGAGGAATAC
AAGCGACTCAGCCAAGAGGTCGAAGAGGAGCTGTCCAACTTCACTGCTTCCCAAGAGCAATATCGCGAGG
AGATGGATGCTGCAATTGCGTCGAAGGATAACAACATCAAGGGATTGGAGCAACGTGTAGAGGCTCTGAC
AACAGAGTTGGCCAGCACCACCAGCGAGCTTAACGGGC"""

dna_sequence = dna_sequence.replace('\n', '').replace(' ', '').upper().strip()

samples = []
for _ in range(10):
    length = random.randint(100, min(3000, len(dna_sequence)))
    start = random.randint(0, len(dna_sequence) - length)
    samples.append(dna_sequence[start:start + length])

lengths = [len(s) for s in samples]

max_dist = 10
distances = [max_dist * (1 - np.log(l)/np.log(max(lengths)) * 0.8) for l in lengths]

print(f"\nDNA Sequence: {len(dna_sequence)} bp")
print("\nFragment Sizes :")
for i, l in enumerate(lengths, 1):
    print(f"  {i}. {l:4d} bp")

fig, ax = plt.subplots(figsize=(5, 14))
ax.set_xlim(0, 3)
ax.set_ylim(0, 15)
ax.set_facecolor('black')

ax.add_patch(plt.Rectangle((1.2, 14.5), 0.6, 0.4, 
                            color='#333', ec='gray', lw=1))

for i, (length, dist) in enumerate(zip(lengths, distances)):
    y = 14.5 - dist
    ax.plot([0.8, 2.2], [y, y], 
            color='white', linewidth=2, solid_capstyle='butt')

for size in [3000, 1500, 500]:
    if size <= max(lengths):
        d = max_dist * (1 - np.log(size)/np.log(max(lengths)) * 0.8)
        y = 14.5 - d
        ax.plot([0.2, 0.6], [y, y], 'w-', lw=1)
        ax.text(0, y, f'{size} bp', ha='right', va='center', 
                color='white', fontsize=12, fontweight='bold')

ax.set_xlim(-1, 3)
ax.axis('off')
ax.set_title('Example of result:', color='white', fontsize=16, 
             loc='left', pad=20, fontweight='normal')

plt.tight_layout()
plt.savefig('./gel_result.png', dpi=150, 
            bbox_inches='tight', facecolor='black')
print("\n✓ Saved: gel_result.png")